# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awstools < Formula
  desc "TUI tools for AWS administration"
  homepage "https://awstools.lmika.dev"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lmika/awstools/releases/download/v0.0.1/awstools_0.0.1_darwin_arm64.tar.gz"
      sha256 "8d6f7632967b250c58eae274d1503415b2cbccdd3bc81e432e7fc6ba2127119e"

      def install
        bin.install "dynamo-browse"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lmika/awstools/releases/download/v0.0.1/awstools_0.0.1_darwin_amd64.tar.gz"
      sha256 "ebf4d8c9f24bc744ed43f15f5d5cf06ea2b709d0c78e13a28ce27131159fa6a2"

      def install
        bin.install "dynamo-browse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lmika/awstools/releases/download/v0.0.1/awstools_0.0.1_linux_amd64.tar.gz"
      sha256 "f06ee56ca3ef305e56b9af5e7d69ff9c1dedd442abcca2890705b40c9117e293"

      def install
        bin.install "dynamo-browse"
      end
    end
  end
end
