# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awstools < Formula
  desc "TUI tools for AWS administration"
  homepage "https://audax.tools"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lmika/audax/releases/download/v0.0.4/audax_0.0.4_darwin_arm64.tar.gz"
      sha256 "6aca5616739767094c7af7fe755467c1cbb423824fee8d84364cb9db4c2b9214"

      def install
        bin.install "dynamo-browse"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lmika/audax/releases/download/v0.0.4/audax_0.0.4_darwin_amd64.tar.gz"
      sha256 "f3e38cfdde782f83874518191cab579f6ea8d37576e0f1cbf0bfd60e29cb1a73"

      def install
        bin.install "dynamo-browse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lmika/audax/releases/download/v0.0.4/audax_0.0.4_linux_amd64.tar.gz"
      sha256 "59fc640d0ae863a9eb71766aea383eb4fefb76c33e5bd93afdd74fa21b1645bf"

      def install
        bin.install "dynamo-browse"
      end
    end
  end
end
